### ISSUE TITLE
Playbook for installing OCP stops everytime at the task - 'Start and enable iptables service'

### ISSUE THREAD

**Issue by kmurudi** [openshift/openshift-cns-testdrive#30]
using this command to run installer- 
ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml

always stops at the mentioned task and then have to stop and run the playbook again..gets deployed second time though.

**Comment by kmurudi** [comment]
works well now, does not stop/hang

**Comment by thoraxe** [comment]
Is this still a problem now that we have made the machines bigger?

**Comment by kmurudi** [comment]
can start installing after 2-3 minutes after ssh-ing into master host. will test again and let know by evening

**Comment by thoraxe** [comment]
Any updates? IDM issues are separate.

**Comment by dmesser** [comment]
I think the workaround Ryan introduced to pre-enable iptables.service and disabled firewalld.service works. You just have to wait for cloud-init to finish and ensure that iptables.service is indeed active. Then you can start the install and it works.
With the previous cloud-init steps this (iptables active) could take 2-3 minutes to be done due to long-running bash scripts. Now with cloud-init executing ansible playbooks it was much faster for me (~40-60 secs after instance boot).
Eventually we can use a wait-condition to signal the user successful rollout of the lab from a CFN standpoint so that the wait-condition would only fire when the last step of cloud-init ran successfully. That would include iptables.service activation and the user only enters the lab environment when this is definitely done and can rollout out OpenShift immediately.
