### ISSUE TITLE
Infrastructure-centric OCS cluster installation fails often with 3.11.98

### ISSUE THREAD

**Issue by blues-man** [openshift/openshift-cns-testdrive#413]
Running latest TestDrive for Admins, Lab 6, installing the infrastructure-centric OCS with playbook `ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/openshift-glusterfs/config.yml` ends up in failing many time at `Waiting for Gluster Pods`

After 3 or more retry it works, was not happening in previous OCP versions.

**Comment by netzzer** [comment]
This issue is related to https://access.redhat.com/solutions/4074511

Current Fix:
Edit /etc/sysconfig/docker
Append --default-pids-limit=-1 to OPTIONS= and save the file
restart docker

Docker version of OCP for Ops test drive in redhat.qwiklabs.com
[root@master cloud-user]# docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-94.gitb2f74b2.el7.x86_64
 Go version:      go1.10.8
 Git commit:      b2f74b2/1.13.1
 Built:           Mon Feb 25 14:45:39 2019
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-94.gitb2f74b2.el7.x86_64
 Go version:      go1.10.8
 Git commit:      b2f74b2/1.13.1
 Built:           Mon Feb 25 14:45:39 2019
 OS/Arch:         linux/am

Upgrading OCS from OCS v3.11.2 to OCS v3.11.3 will fix the issue but this is not easily done given the OCS images files are include in the AMI to create the lab instances.
